
services:
  # Balanceador de carga
  load_balancer:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - my_network
          

  web1:
    build: ./web_servers/web1
    networks:
      - my_network
    ports:
      - "8081:8080"  # Exponer web1 en el host en el puerto 8081

  web2:
    build: ./web_servers/web2
    networks:
      - my_network
    ports:
      - "8082:8080"  # Exponer web2 en el host en el puerto 8082

  
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter
    networks:
      - my_network 
    ports:
      - "9113:9113"
    environment:
      - NGINX_SERVER=http://load_balancer/nginx_status  # Apunta al nombre del contenedor y no a localhost


  # Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  # Grafana
  grafana:
    build: ./monitoring/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning  # Configuración automática
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards     # Paneles predefinidos
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
